apiVersion: v1
kind: Service
metadata:
  name: queue-master
  labels:
    name: queue-master
  namespace: sock-shop
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    name: queue-master
