replicaCount: 1

image:
  repository: weaveworksdemos/queue-master
  tag: "0.3.1"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 300Mi

service:
  type: ClusterIP
  port: 80

env:
  JAVA_OPTS: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"

nodeSelector:
  beta.kubernetes.io/os: linux
