replicaCount: 1

image:
  repository: weaveworksdemos/carts
  tag: "0.4.8"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi

service:
  type: ClusterIP
  port: 80

db:
  image: mongo
  port: 27017

nodeSelector:
  beta.kubernetes.io/os: linux
