apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: sock-shop
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      initContainers:
      - name: fix-mongo-permissions
        image: busybox
        command: ['sh', '-c', 'chown -R 999:999 /data/db']
        volumeMounts:
        - name: user-db-storage
          mountPath: /data/db
      containers:
      - name: user-db
        image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        ports:
        - containerPort: {{ .Values.db.port }}
        volumeMounts:
        - mountPath: /data/db
          name: user-db-storage
      volumes:
      - name: user-db-storage
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.claimName }}
