apiVersion: v1
kind: Service
metadata:
  name: carts-db
  labels:
    name: carts-db
  namespace: sock-shop
spec:
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    name: carts-db
