replicaCount: 1

image:
  repository: weaveworksdemos/user
  tag: "0.4.7"
  pullPolicy: IfNotPresent

db:
  image:
    repository: weaveworksdemos/user-db
    tag: "0.3.0"
  port: 27017

resources:
  limits:
    cpu: 300m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

mongo:
  host: user-db
  port: 27017

service:
  type: ClusterIP
  port: 80

pvc:
  claimName: user-db-pvc

nodeSelector: {}
